chore: remove collection import
googleapis/python-firestore pull request #186
Opened 2020-09-08 12:35 UTC by HemangChothani

Fixes #183

2020-09-08 14:41 UTC, HemangChothani commented
Unit test failed due new to release of protobuf lib and resolved in https://github.com/googleapis/python-firestore/pull/185 PR

2020-09-14 17:43 UTC, tseaver requested changes

2020-09-14 17:43 UTC, tseaver commented on google/cloud/firestore_v1/field_path.py
> +from collections import abc as collections_abc
Rather than maintaining the alias, please just use `collections.abc` here (and below), e.g.:

```suggestion
import collections.abc
```

2020-09-16 17:57 UTC, tseaver approved these changes

2020-09-16 18:10 UTC, merged