fix: remove unnecessary dependency on libcst and scripts
googleapis/python-firestore pull request #220
Opened 2020-10-08 12:00 UTC by HemangChothani

Fixes #218

2020-10-08 17:39 UTC, tseaver requested changes
#218 says:

> Remove libcst as a dependency and edit the fixup script to raise an error if the library is not installed.

Please restore the scripts, and edit as directed.

2020-10-09 07:40 UTC, HemangChothani commented
@tres I found in [bigquery PR ](https://github.com/googleapis/python-bigquery/pull/308), that they deleted the file and enter in exclude in syth.py so followed the same. Please guide the correct way.

2020-10-09 14:22 UTC, tseaver commented
@busunkim96 you specified in #218 that the fix was to remove the dependency, and update the script(s) to raise an error if `libcst` could not be imported.  Please clarify.

2020-10-20 05:04 UTC, HemangChothani commented
@busunkim96 Could you please give some clarification?

2020-10-20 16:48 UTC, tswast commented
> was the script not useful for bigquery by chance?

Correct. It was useless for BigQuery since we wrap the client objects in the BigQuery Storage API and in the core library we don't use the client objects at all. We only need the generator to make the compiled protos in the core library.

Still, I think it makes sense to make `libcst` an optional dependency, as it conflicts with the `awssdk` library due to incompatible `YAML` version requirements.

2020-10-21 20:07 UTC, tseaver requested changes

2020-10-21 20:07 UTC, tseaver commented on scripts/fixup_admin_v1_keywords.py
> +    raise ImportError(exception.__class__.__name__ + ": " + exception.msg)
Pointless to raise another `ImportError` without extra info.  Instead, please add the message specified by @crwilcox, suggesting that the user run  `python -m pip install "libcst >= 0.2.5"`.

2020-10-21 20:07 UTC, tseaver commented on scripts/fixup_firestore_admin_v1_keywords.py
> +#nox
Stray line.  Please remove

2020-10-21 20:07 UTC, tseaver commented on scripts/fixup_firestore_admin_v1_keywords.py
> +    raise ImportError(exception.__class__.__name__ + ": " + exception.msg)
As above here.

2020-10-21 20:07 UTC, tseaver commented on scripts/fixup_firestore_v1_keywords.py
> +
As above here.

2020-10-21 20:07 UTC, tseaver commented on setup.py
> -    ],
Remove this change, please.

2020-10-21 20:07 UTC, tseaver commented on synth.py
> +        ],
Remove this change, please.

2020-10-21 20:07 UTC, tseaver commented on synth.py
> +        ],
Remove this change, please.

2020-10-22 05:45 UTC, HemangChothani commented on scripts/fixup_firestore_v1_keywords.py
> +
Done, not sure why didn't reflect here.

2020-10-22 19:55 UTC, tseaver approved these changes

2020-10-23 19:34 UTC, crwilcox approved these changes

2020-10-23 20:51 UTC, merged