docs: add documentation for documentsnapshot class
googleapis/python-firestore pull request #263
Opened 2020-11-27 08:24 UTC by HemangChothani

Fixes #262 

- The document was there till the version `1.9.0` because the class was in the `document.py` file, but after that it was vanished as class moved to the `base_document.py` file.

2021-02-03 17:48 UTC, tseaver requested changes

2021-02-03 17:48 UTC, tseaver commented on docs/document.rst
> +  :show-inheritance:
We needed to document the whole `base_document` model, since done in PR #278.
```suggestion
```

2021-02-03 17:49 UTC, tseaver approved these changes

2021-02-04 23:24 UTC, crwilcox approved these changes

2021-02-05 01:19 UTC, merged