testing: use pytest idioms for unit tests
googleapis/python-firestore pull request #499
Opened 2021-11-30 19:10 UTC by tseaver

Closes #498.

2021-11-30 19:33 UTC, tseaver commented
Reviewers:  this is a big PR, and mostly involves repetition of the same few transforms:

- Use normal `assert` rather than `self.assert*`.
- Replace `self.assertRaises` with `pytest.raises`.
- Convert testcase helper methods to module-scope functions.
- Drop use of the `unittest.TestCase` base class, converting testcase methods to module-scope functions.
- Minor cleanups of module-scope imports.

2021-12-06 23:50 UTC, tseaver commented
4ff4506 seems to have broken `Watch.on_snapshot` -- I will check it out tomorrow.

All the earlier "test refactoring" commits should be reviewable as it.

2021-12-07 15:55 UTC, tseaver commented
I've rebased the branch to remove the last two commits (4ff4506 and 10eb32f), leaving this PR as purely unit-test refactoring.

2021-12-09 02:01 UTC, tswast requested changes
A few minor issues, but otherwise LGTM

2021-12-09 14:27 UTC, tseaver commented on tests/unit/v1/test__helpers.py
> +    document_path = "projects/project-id/databases/(default)/" "documents/document-id"
866bf1d for this and ff.

2021-12-09 14:28 UTC, tseaver commented on tests/unit/v1/test_transforms.py
> +            _make_numeric_value(invalid_value)
e723d5d

The first argument needs to be a comma-delimited string.

2021-12-09 14:28 UTC, tseaver commented on tests/unit/v1/test_transforms.py
> +        assert inst.value == value
e723d5d

2021-12-09 14:28 UTC, tseaver commented on tests/unit/v1/test_base_client.py
> +    return BaseClient(*args, **kwargs)
Nope -- the test was actually not working as intended (it was copy-pasta from the three-way split).

2021-12-09 14:29 UTC, tseaver commented on tests/unit/v1/test_base_client.py
> +    documents = [mock.Mock(_document_path=path) for path in expected_doc_paths]
I'd prefer not:  unit tests should rely as little as possible on other modules from the same package.

2021-12-09 14:45 UTC, tseaver commented on tests/unit/v1/test_client.py
> +def test_client__firestore_api_property():
I'm pretty sure I added it to provide explicit coverage for the property, which previously was covered only incidentally (part of that `Client` vs. `BaseClient` bit above).

2021-12-09 14:55 UTC, tseaver commented on tests/unit/v1/test_query.py
> +_not_passed = object()
Cleaning out module-scope imports from the test module:  the `gapic_v1` module is now imported inside the helper function.

2021-12-09 15:00 UTC, tseaver commented on tests/unit/v1/test_base_document.py
> +    document != other
f888567

2021-12-09 15:01 UTC, tseaver commented on tests/unit/v1/test_bundle.py
> +        # assert re_serialized == _helpers.deserialize_bundle(re_serialized, client=client).build()
1ba0f41617ad95e5ef5d07acf0d63aa12397a8a2

2021-12-09 15:01 UTC, tseaver commented on tests/unit/v1/test_client.py
> +    pytest.raises(TypeError, client.recursive_delete, object())
Nope. 5c84656

2021-12-09 15:01 UTC, tseaver commented on tests/unit/v1/test_query.py
> +    assert snapshot.reference._path == ("dee", "sleep")
25b32f9

2021-12-09 15:02 UTC, tseaver commented on tests/unit/v1/test_transaction.py
> +    assert firestore_api.commit.mock_calls, [commit_call == commit_call]
acf9f8d

2021-12-13 15:37 UTC, tswast approved these changes

2021-12-21 18:42 UTC, merged